# Generated by Django 4.1.2 on 2022-10-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0004_role_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ext',
            name='rol_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.role'),
        ),
    ]
