# Generated by Django 4.1.2 on 2022-11-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0007_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='doc_id',
        ),
        migrations.AddField(
            model_name='leave',
            name='doc_id',
            field=models.ManyToManyField(blank=True, null=True, to='hmsapp.doctor'),
        ),
    ]
