# Generated by Django 4.1.2 on 2022-11-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0009_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approve',
            field=models.IntegerField(null=True),
        ),
    ]
